In [1]:
import pandas as pd

In [38]:
dataset=pd.read_csv('E:\Datasets\CSV\movie_users.csv')

In [40]:
dataset.std(axis=1)
dataset.std(axis=0)
dataset.mean(axis=1)
dataset.mean(axis=0)
dataset.max(axis=1)
dataset.max(axis=0)
dataset.min(axis=1)
dataset.min(axis=0)
dataset.sum(axis=1)
dataset.sum(axis=0)
dataset.drop('genre',axis=1)
dataset.drop(2,axis=0)

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
5,8.9,12 Angry Men,NOT RATED,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [26]:
dataset

,star_rating,title,content_rating,genre,duration
0,9.3,The Shawshank Redemption,R,Crime,142
1,9.2,The Godfather,R,Crime,175
2,9.1,The Godfather: Part II,R,Crime,200
3,9.0,The Dark Knight,PG-13,Action,152
4,8.9,Pulp Fiction,R,Crime,154
...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116
975,7.4,Back to the Future Part III,PG,Adventure,118
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138
977,7.4,Poltergeist,PG,Horror,114
978,7.4,Wall Street,R,Crime,126